samples:
    CN20448_BKDL190826856-1a_1: CN20448_BKDL190826856-1a_1.fq
  
adapter:
    adapter1: GTTTAAGAGCTATGCTGGAAACAGCATAGCAAGTTTAAATAAGGCTAGTCCGTTATCAACTTGAAAAAGTGGCACCGAGT
    adapter2: ACTCGGTGCCACTTTTTCAAGTTGATAACGGACTAGCCTTATTTAAACTTGCTATGCTGTTTCCAGCATAGCTCTTAAAC
    adapter3: CGATCGATTTGAGCCTGCTTTATATATCTTGTGGAAAGGACGAAACACCG
    adapter4: CGGTGTTTCGTCCTTTCCACAAGATATATAAAGCAGGCTCAAATCGATCG

fasta:
    CN20448: CN20448.fa    

